### ISSUE TITLE
Notifications Hang system and use 100% CPU [$65]

### ISSUE THREAD

**Issue by silver-dragon** [mate-desktop/mate-notification-daemon#113]
When ever I get a notification from the daemon it causes the computer to slow way down and when I check the processes I see that the is using 100% of the cpu. The computer will return to normal after a sigterm the process. Most of my notifications come from Opera browser I don't know if there is a related compatibility issue. Screenshot -> https://www.dropbox.com/s/rwpa95enw9syegy/mate-notification-daemon-crash.png?raw=1
##

**Comment by absemetov** [comment]
Linux Mint 18.1, 64bit ThinkPad x121e
In addition, I have the upper right corner desktop not working
After killing daemon, mouse starts to click in this area

**Comment by iamanikeev** [comment]
Had the same issue just now, reproduced it when enabled notifications in Opera, and received a notification from a pinned telegram.web tab. Other notifications (e.g. from Slack) didn't cause this issue.

**Comment by Finwood** [comment]
Same here. Reproducible from Opera with Telegram, Slack and WhatsApp notifications.

_Linux Mint 18.1 Serena (4.4.0-53-generic x86_64), MATE 1.16.1, Opera 43.0.2442.1144_

**Comment by hipkomh** [comment]
Same here. wechat, wx.qq.com. Tks~

**Comment by glum-psyche** [comment]
The same issue. All Opera notifications cause the overhead.

_Ubuntu 16.04.1 (4.8.0-57-genericx 86_64), MATE 1.16.2, Opera 46.0.2597.26_

**Comment by edisonrocha** [comment]
Same here. Opera and Rambox notifications.

Ubuntu 17.04, Opera 46.0.2597.57

**Comment by p-m** [comment]
Steps to reproduce:

1.) On an openSUSE Leap 42.3 system, install packages emacs-x11, fvwm and mate-notification-daemon.

2.) Start fvwm session.

3.) Start this command:
`emacs -Q --eval "(progn (require 'notifications) (notifications-notify :title \"Test\" :timeout 2200000 :actions '(\"one\" \"two\")))"`

Result: mate-notification-daemon hangs with 100% CPU utilisation.

Peter

**Comment by snaiperskaya96** [comment]
Please have a look at the linked PR and let me know (#122)

**Comment by p-m** [comment]
Could you please send the commands for building with your pull-request?
Something like:
git clone ulr
git merge your-pull-request
./configure
make

TIA, Peter

**Comment by snaiperskaya96** [comment]
Nothing really different form the usual mate-notification-daemon process.
I believe you can build it by doing something like this:
```
git clone https://github.com/snaiperskaya96/mate-notification-daemon.git
cd mate-notification-daemon
git checkout opera-notifications-memory-leak
./autogen.sh
make
sudo make install
```

There might be a few dependencies to install that i cannot actually remember, just post here if you need some help :)

Also please close the old process if there is any active and consider rebooting/reloading the session if you cannot notice any change

**Comment by p-m** [comment]
On Tue, Aug 08 2017, Jury Verrigni wrote:

> git checkout opera-notifications-memory-leak

Thanks, seems to be easy to compile a PR.

The issue seems to be solved here.

Thanks, Peter

**Comment by snaiperskaya96** [comment]
Hi!
Fixed it. The countdown is back.
Please note that the name of the pr is misleading. The cause of this problem is a leak given by the way the pie used to be draft. I rewrote it and seems to work correctly.
Test it and let me know.

Cheers

**Comment by snaiperskaya96** [comment]
Okay just realised that the opera issue and the countdown one weren't related 😄  Will merge the two fixes as soon as i have time

**Comment by snaiperskaya96** [comment]
Ignore my previous theories. I came to the conclusion that the problem was due to opera setting the timeout to MAX_INT instead of 0 to make an endless notification, i think. Should be definitely fixed now.

**Comment by p-m** [comment]
On Wed, Aug 09 2017, Jury Verrigni wrote:

> Should be definitely fixed now.

It seems, that there is still a problem with the Nodoka theme.
The daemon hangs with 100% CPU usage. Please try this:

emacs -Q --eval "(progn (require 'notifications) (notifications-notify :title \"Test\" :timeout 2200000 :actions '(\"key\" \"text\")) (kill-emacs))"

No problem with timeout = 2100000.

-- 
           Peter

**Comment by snaiperskaya96** [comment]
True, I think we should deal with realistic timeouts though. Using 30 minutes instead of 0 (infinite) sounds silly to me, i think we should discuss with the team to limit this to, say, 20 minutes and eventually set the timeout to 0 if > 20 minutes

**Comment by p-m** [comment]
On Wed, Aug 09 2017, Jury Verrigni wrote:

> True, I think we should deal with realistic timeouts though. Using 30
> minutes instead of 0 (infinite) sounds silly to me,

There are use cases where this is not silly. Sometimes I use a timeout
of 2 hours or similar.

Since there is really no reason, why this should not work, I've
investigated myself. Please find here the patch, that solves the issue:

diff --git a/src/daemon/daemon.c b/src/daemon/daemon.c
index 72b94a4..4b81c3c 100644
--- a/src/daemon/daemon.c
+++ b/src/daemon/daemon.c
@@ -743,7 +743,7 @@ static void _calculate_timeout(NotifyDaemon* daemon, NotifyTimeout* nt, int time
 
 		theme_set_notification_timeout(nt->nw, timeout);
 
-		glong usec = timeout * 1000;  /* convert from msec to usec */
+		glong usec = timeout * 1000L;  /* convert from msec to usec */
 
 		/*
 		 * If it's less than 0, wrap around back to MAXLONG.

-- 
           Peter

**Comment by snaiperskaya96** [comment]
Works flawlessy, i completely mislooked at it. Thank you, will push this change instead of mines

**Comment by snaiperskaya96** [comment]
Sorry about the claim, thought it was other stuff on caja :)

**Comment by monsta** [comment]
The fix is now released in version 1.18.1.
